version: "3.5"

services:
  server:
    build: .
    image: debug-server:1.0
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
      - 6379:6379
    entrypoint: dlv debug --headless --listen=:6379 --log --api-version=2
